# Preprocessing configuration for the dataset

preprocessing:
  # Columns to be used in the model
  features_columns:
    - Basic_Demos-Enroll_Season
    - Basic_Demos-Age
    - Basic_Demos-Sex
    - CGAS-Season
    - CGAS-CGAS_Score
    - Physical-Season
    - Physical-BMI
    - Physical-Height
    - Physical-Weight
    - Physical-Waist_Circumference
    - Physical-Diastolic_BP
    - Physical-HeartRate
    - Physical-Systolic_BP
    - Fitness_Endurance-Season
    - Fitness_Endurance-Max_Stage
    - Fitness_Endurance-Time_Mins
    - Fitness_Endurance-Time_Sec
    - FGC-Season
    - FGC-FGC_CU
    - FGC-FGC_CU_Zone
    - FGC-FGC_GSND
    - FGC-FGC_GSND_Zone
    - FGC-FGC_GSD
    - FGC-FGC_GSD_Zone
    - FGC-FGC_PU
    - FGC-FGC_PU_Zone
    - FGC-FGC_SRL
    - FGC-FGC_SRL_Zone
    - FGC-FGC_SRR
    - FGC-FGC_SRR_Zone
    - FGC-FGC_TL
    - FGC-FGC_TL_Zone
    - BIA-Season
    - BIA-BIA_Activity_Level_num
    - BIA-BIA_BMC
    - BIA-BIA_BMI
    - BIA-BIA_BMR
    - BIA-BIA_DEE
    - BIA-BIA_ECW
    - BIA-BIA_FFM
    - BIA-BIA_FFMI
    - BIA-BIA_FMI
    - BIA-BIA_Fat
    - BIA-BIA_Frame_num
    - BIA-BIA_ICW
    - BIA-BIA_LDM
    - BIA-BIA_LST
    - BIA-BIA_SMM
    - BIA-BIA_TBW
    - PAQ_A-Season
    - PAQ_A-PAQ_A_Total
    - PAQ_C-Season
    - PAQ_C-PAQ_C_Total
    - SDS-Season
    - SDS-SDS_Total_Raw
    - SDS-SDS_Total_T
    - PreInt_EduHx-Season
    - PreInt_EduHx-computerinternet_hoursday
    - sii
    - time_series_columns:
        - stat_0
        - stat_1
        - stat_2
        - stat_3
        - stat_4
        - stat_5
        - stat_6
        - stat_7
        - stat_8
        - stat_9
        - stat_10
        - stat_11
        - stat_12
        - stat_13
        - stat_14
        - stat_15
        - stat_16
        - stat_17
        - stat_18
        - stat_19
        - stat_20
        - stat_21
        - stat_22
        - stat_23
        - stat_24
        - stat_25
        - stat_26
        - stat_27
        - stat_28
        - stat_29
        - stat_30
        - stat_31
        - stat_32
        - stat_33
        - stat_34
        - stat_35
        - stat_36
        - stat_37
        - stat_38
        - stat_39
        - stat_40
        - stat_41
        - stat_42
        - stat_43
        - stat_44
        - stat_45
        - stat_46
        - stat_47
        - stat_48
        - stat_49
        - stat_50
        - stat_51
        - stat_52
        - stat_53
        - stat_54
        - stat_55
        - stat_56
        - stat_57
        - stat_58
        - stat_59
        - stat_60
        - stat_61
        - stat_62
        - stat_63
        - stat_64
        - stat_65
        - stat_66
        - stat_67
        - stat_68
        - stat_69
        - stat_70
        - stat_71
        - stat_72
        - stat_73
        - stat_74
        - stat_75
        - stat_76
        - stat_77
        - stat_78
        - stat_79
        - stat_80
        - stat_81
        - stat_82
        - stat_83
        - stat_84
        - stat_85
        - stat_86
        - stat_87
        - stat_88
        - stat_89
        - stat_90
        - stat_91
        - stat_92
        - stat_93
        - stat_94
        - stat_95

  # Categorical columns to be label-encoded
  categorical_columns:
    - Basic_Demos-Enroll_Season
    - CGAS-Season
    - Physical-Season
    - Fitness_Endurance-Season
    - FGC-Season
    - BIA-Season
    - PAQ_A-Season
    - PAQ_C-Season
    - SDS-Season
    - PreInt_EduHx-Season

  # Preprocessing steps for missing values and type conversion
  missing_values:
    impute_strategy: median
    fill_missing_categories: "Missing"

  # Function to handle missing and categorical columns
  update_function:
    replace_missing_with: "Missing"
    convert_to_category: true
